SET SQL_SAFE_UPDATES = 0;
-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS EXERCICIOEXTRA;
-- CRIANDO O BANCO DE DADOS
CREATE DATABASE EXERCICIOEXTRA;
-- CONECTANDO AO BANCO DE DADOS
USE EXERCICIOEXTRA;

-- CRIANDO AS TABELAS
CREATE TABLE LIVRO (
IDLIVRO INT NOT NULL AUTO_INCREMENT,
NOME_LIVRO VARCHAR (50) NOT NULL,
AUTOR VARCHAR (150) NOT NULL, 
ANO_PUBLICACAO INT ,
GENERO VARCHAR (30),
PRIMARY KEY (IDLIVRO)
);
-- INCLUINDO DADOS 
INSERT INTO LIVRO (NOME_LIVRO, AUTOR, ANO_PUBLICACAO, GENERO) VALUES ('DOM CASMURRO', 'MACHADO DE ASSIS', 1899, 'ROMANCE');
INSERT INTO LIVRO (NOME_LIVRO, AUTOR, ANO_PUBLICACAO, GENERO) VALUES ('O CORTIÇO', 'ALUÍSIO AZEVEDO', 1890, 'NATURALISMO');
INSERT INTO LIVRO (NOME_LIVRO, AUTOR, ANO_PUBLICACAO, GENERO) VALUES ('IRACEMA', 'JOSÉ DE ALENCAR', 1865, 'ROMANTISMO');

UPDATE LIVRO
SET ANO_PUBLICACAO = ANO_PUBLICACAO +1
WHERE ANO_PUBLICACAO<1900;

ALTER TABLE LIVRO ADD DISPONIVEL CHAR (3) AFTER GENERO;

UPDATE LIVRO SET DISPONIVEL = CASE
WHEN GENERO = 'ROMANCE' THEN 'SIM' 
ELSE 'NAO'
END;

SELECT* FROM LIVRO;