SET SQL_SAFE_UPDATES = 0;
-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO2;
-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO2;
-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO2;

-- CRIANDO AS TABELAS
CREATE TABLE NOTA (
IDNOTA INT NOT NULL AUTO_INCREMENT,
ALUNO VARCHAR (120) NOT NULL,
BIN_1 DECIMAL(5,2) ,
BIN_2 DECIMAL(5,2) ,
BIN_3 DECIMAL(5,2) ,
BIN_4 DECIMAL(5,2) ,
MEDIA DECIMAL(5,2) , 
RESULTADO CHAR (7),
PRIMARY KEY (IDNOTA)
);
-- INCLUINDO OS DADOS 
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 1' , '10.00', '8.00', '4.00','4.00', '6.50', 'RUIM');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 2' , '7.00', '9.00', '8.00','10.00', '8.50', 'REGULAR');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 3' , '8.00', '10.00', '6.00','7.00', '7.75', 'REGULAR');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 4' , '9.00', '6.00', '4.00','6.00', '6.25', 'RUIM');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 5' , '5.00', '10.00', '5.00','9.00', '7.25', 'REGULAR');

UPDATE NOTA
SET BIN_2 = BIN_2+1
WHERE BIN_2 <10;

ALTER TABLE NOTA ADD RECUPERACAO DOUBLE AFTER MEDIA;

SELECT * 
FROM NOTA 
WHERE MEDIA <> (BIN_1 + BIN_2 + BIN_3+BIN_4) / 4 ;

UPDATE NOTA
SET RECUPERACAO = 7.00 - MEDIA
WHERE MEDIA <7.00;

UPDATE NOTA 
SET RESULTADO =
CASE 
WHEN MEDIA + RECUPERACAO >= 7.00 THEN 'REGULAR'
ELSE 'RUIM' 
END;

SELECT * 
FROM NOTA ;
