SET SQL_SAFE_UPDATES = 0;
-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO3;
-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO3;
-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO3;

-- CRIANDO AS TABELAS
CREATE TABLE PESQUISA (
IDPESQUISA INT AUTO_INCREMENT,
NOME VARCHAR (120) NOT NULL,
CIDADE VARCHAR (120) NOT NULL,
IDADE INT NOT NULL,
NOTA DECIMAL(5,2) NOT NULL,
PRIMARY KEY (IDPESQUISA)
);
-- INCLUINDO DADOS 
INSERT INTO PESQUISA (NOME, CIDADE, IDADE, NOTA) VALUES ('PEDRO', 'SÃO PAULO', 34, 83.0);
INSERT INTO PESQUISA (NOME, CIDADE, IDADE, NOTA) VALUES ('MARIA', 'SÃO PAULO', 23, 59.0);
INSERT INTO PESQUISA (NOME, CIDADE, IDADE, NOTA) VALUES ('JANAINA', 'RIO DE JANEIRO', 32, 86.0);
INSERT INTO PESQUISA (NOME, CIDADE, IDADE, NOTA) VALUES ('WONG', 'BRASILIA', 43, 89.0);
INSERT INTO PESQUISA (NOME, CIDADE, IDADE, NOTA) VALUES ('ROBERTO', 'SALVADOR', 38, 98.0);
INSERT INTO PESQUISA (NOME, CIDADE, IDADE, NOTA) VALUES ('MARCO', 'CURITIBA', 31, 61.0);
INSERT INTO PESQUISA (NOME, CIDADE, IDADE, NOTA) VALUES ('PAULA', 'BELO HORIZONTE', 34, 44.0);

UPDATE PESQUISA SET IDADE = 28 WHERE NOME = 'ROBERTO';
UPDATE PESQUISA SET NOTA = 69.2, CIDADE ='FLORIANOPOLIS' WHERE NOME= 'MARIA';

DELETE FROM PESQUISA WHERE IDADE>40;


SELECT *
FROM PESQUISA;