SET SQL_SAFE_UPDATES = 0;
-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO1;
-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO1;
-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO1;

-- CRIANDO AS TABELAS
CREATE TABLE PESSOA (
IDPESSOA INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(120) NOT NULL,
CPF CHAR(11) NOT NULL,
IDADE INT NOT NULL,
PRIMARY KEY (IDPESSOA)
);
-- INCLUINDO OS DADOS 
INSERT INTO PESSOA (NOME, CPF, IDADE ) VALUES ('JOSE DA SILVA' , '05578130688', 53);
INSERT INTO PESSOA (NOME, CPF, IDADE ) VALUES ('MARIA MARTA' , '72364020255', 45);
INSERT INTO PESSOA (NOME, CPF, IDADE ) VALUES ('JOÃO CARLOS' , '99955203695', 50);
INSERT INTO PESSOA (NOME, CPF, IDADE ) VALUES ('JOANNA LIMA' , '02287965222', 28);
-- EXERCICIO 4

-- EXERCICIO 5
UPDATE PESSOA 
SET IDADE = 28 
WHERE NOME = 'JOÃO CARLOS';

UPDATE PESSOA 
SET NOME = 'MARIA JULIA', IDADE = 45
WHERE NOME = 'MARIA MARTA';

-- EXERCICIO 7
DELETE FROM PESSOA WHERE IDADE > 40;

SELECT * 
FROM PESSOA ;

