SET SQL_SAFE_UPDATES = 0;
-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO4;
-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO4;
-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO4;

-- CRIANDO AS TABELAS
CREATE TABLE CLIENTE (
IDCLIENTE INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR (120) NOT NULL,
PRIMARY KEY(IDCLIENTE)
);

CREATE TABLE PEDIDO (
IDPEDIDO INT NOT NULL AUTO_INCREMENT,
IDCLIENTE INT NOT NULL ,
DT_PEDIDO DATE NOT NULL,
PRODUTO VARCHAR(120) NOT NULL, 
QTDE INT,
PRIMARY KEY (IDPEDIDO),
FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);
INSERT INTO CLIENTE (NOME) VALUES ('GROE'), ('GEROMEL'), ('KANNEMAN'), ('LUAN');
INSERT INTO PEDIDO (IDCLIENTE, DT_PEDIDO, PRODUTO, QTDE) VALUES ('2','2025-08-06', 'XIS', 15);
INSERT INTO PEDIDO (IDCLIENTE, DT_PEDIDO, PRODUTO, QTDE) VALUES ('3','2025-08-06', 'XISSALADA', 1);
INSERT INTO PEDIDO (IDCLIENTE, DT_PEDIDO, PRODUTO, QTDE) VALUES ('3','2025-08-06', 'XISCALABRESA', 1);
INSERT INTO PEDIDO (IDCLIENTE, DT_PEDIDO, PRODUTO, QTDE) VALUES ('4','2025-08-06', 'XISBACON', 2);
INSERT INTO PEDIDO (IDCLIENTE, DT_PEDIDO, PRODUTO, QTDE) VALUES ('4','2025-08-06', 'XISFRANGO', 1);

UPDATE PEDIDO SET QTDE = QTDE +2 WHERE IDCLIENTE = '2';
UPDATE PEDIDO SET QTDE = QTDE +3 WHERE IDCLIENTE = '3';
DELETE FROM PEDIDO WHERE IDCLIENTE = 4;
DELETE FROM CLIENTE WHERE IDCLIENTE = 4;


SELECT *
FROM PEDIDO; 

SELECT *
FROM CLIENTE; 