SET SQL_SAFE_UPDATES = 0;
-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO2;
-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO2;
-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO2;

-- CRIANDO AS TABELAS
CREATE TABLE NOTA (
IDNOTA INT NOT NULL AUTO_INCREMENT,
ALUNO VARCHAR (120) NOT NULL,
BIN_1 DECIMAL(5,2) ,
BIN_2 DECIMAL(5,2) ,
BIN_3 DECIMAL(5,2) ,
BIN_4 DECIMAL(5,2) ,
MEDIA DECIMAL(5,2) , 
RESULTADO CHAR (7),
PRIMARY KEY (IDNOTA)
);
-- INCLUINDO OS DADOS 
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 1' , '10.00', '8.00', '4.00','4.00', '6.50', 'RUIM');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 2' , '7.00', '9.00', '8.00','10.00', '8.50', 'REGULAR');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 3' , '8.00', '10.00', '6.00','7.00', '7.75', 'REGULAR');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 4' , '9.00', '6.00', '4.00','6.00', '6.25', 'RUIM');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 5' , '5.00', '10.00', '5.00','9.00', '7.25', 'REGULAR');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 6' , '8.00', '8.00', '4.00','9.00', '7.25', 'REGULAR');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 7' , '10.00', '5.00', '9.00','4.00', '7.00', 'REGULAR');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 8' , '8.00', '4.00', '7.00','10.00', '7.25', 'REGULAR');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 9' , '4.00', '7.00', '9.00','4.00', '6.00', 'REGULAR');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 10' , '10.00', '5.00', '10.00','7.00', '8.00', 'REGULAR');
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA, RESULTADO ) VALUES ('ALUNO 11' , '10.00', '8.00', '4.00','6.00', '7.00', 'REGULAR');

UPDATE NOTA
SET BIN_2 = BIN_2+1
WHERE BIN_2 <10;

UPDATE NOTA SET ALUNO = 'GROE' WHERE ALUNO = 'ALUNO 1';
UPDATE NOTA SET ALUNO = 'EDILSON' WHERE ALUNO = 'ALUNO 2';
UPDATE NOTA SET ALUNO = 'GEROMEL' WHERE ALUNO = 'ALUNO 3';
UPDATE NOTA SET ALUNO = 'KANNEMAM' WHERE ALUNO = 'ALUNO 4';
UPDATE NOTA SET ALUNO = 'CORTEZ' WHERE ALUNO = 'ALUNO 5';
UPDATE NOTA SET ALUNO = 'JAILSON' WHERE ALUNO = 'ALUNO 6';
UPDATE NOTA SET ALUNO = 'ARTHUR' WHERE ALUNO = 'ALUNO 7';
UPDATE NOTA SET ALUNO = 'RAMIRO' WHERE ALUNO = 'ALUNO 8';
UPDATE NOTA SET ALUNO = 'LUAN' WHERE ALUNO = 'ALUNO 9';
UPDATE NOTA SET ALUNO = 'FERNANDINHO' WHERE ALUNO = 'ALUNO 10';
UPDATE NOTA SET ALUNO = 'LUCAS BARRIOS' WHERE ALUNO = 'ALUNO 11';

DELETE FROM NOTA WHERE ALUNO = 'FERNANDINHO';
INSERT INTO NOTA (ALUNO, BIN_1, BIN_2, BIN_3, BIN_4, MEDIA) VALUES ('CEBOLINHA', 7.00,8.00,9.00,10.00, 8.50);

ALTER TABLE NOTA ADD RECUPERACAO DOUBLE AFTER MEDIA;

SELECT * 
FROM NOTA 
WHERE MEDIA <> (BIN_1 + BIN_2 + BIN_3+BIN_4) / 4 ;

UPDATE NOTA
SET RECUPERACAO = 7.00 - MEDIA
WHERE MEDIA <7.00;

UPDATE NOTA 
SET RESULTADO =
CASE 
WHEN MEDIA + RECUPERACAO >= 7.00 THEN 'REGULAR'
WHEN MEDIA BETWEEN 7.00 AND 9.00 THEN 'BOM'
WHEN MEDIA BETWEEN 9.00 AND 10.00 THEN 'OTIMO'
ELSE 'RUIM' 
END;


SELECT * 
FROM NOTA ;
